INTO_WebApp/INTO/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Shared;
using BLL.Student;
using DAL.Shared;
using INTO.Controllers.Shared;
using INTO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace INTO.Controllers
{
    public class StudentController : SecureController<StudentController>
    {
        public StudentController(IConfiguration configuration) : base(configuration) { }
        public IActionResult Index()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult DashboardDisplay(int? uId = null, int? langId = 1)
        {
            //User user = new User();
            //user = UserDB.GetUser(uId, langId, GetConfiguration().GetConnectionString("DefaultConnection"));
            //return View(new LoginModel { User = user });
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public JsonResult EditProfile(int UId, DateTime dOB, string schoolName, int schoolYear, int countryId, string address, string address2, string city)
        {
            Student student = new Student();
            LoginModel loginModel = new LoginModel();
            student.UserId = UId;
            student.DOB = dOB;
            student.SchoolName = schoolName;
            student.SchoolYear = schoolYear;
            student.LocationSettings = new LocationSettings
            {
                Country = new Country
                {
                    Id = countryId
                },
                City = city,
                Address = address,
                SecondAddress = address2
            };
            //loginModel.CountryId = countryId;
            //loginModel.User.Address = address;
            //loginModel.User.Address2 = address2;
            //loginModel.User.City = city;

            //we can send user instead of address,address2,city each param alone
            Student studentProfile = UserDB.EditStudentProfile(student, countryId,address,address2,city, GetConfiguration().GetConnectionString("DefaultConnection"));
            return Json(studentProfile);
        }
        public IActionResult StudentHome(LoginModel loginModel)
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    //studentModel.Resources = LookUpDB.GetTranslation("Pages.StudentHome", 1, GetConfiguration().GetConnectionString(DEFAULT_CONNECTION));
                    //studentModel.Globals = LookUpDB.GetTranslation("Global", 1, GetConfiguration().GetConnectionString(DEFAULT_CONNECTION));
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult Booking()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult HelpCenter()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult ContactUs()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult EditPassword(int? usrId = null, int? langId = 1)
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    //User user = new User();
                    //user = UserDB.GetUser(usrId, langId, GetConfiguration().GetConnectionString("DefaultConnection"));
                    //return View(new LoginModel { User = user });
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
            
        }
        public JsonResult EditNewPassword(int UId, string ConfirmNewPasswrod)
        {
            Student student = new Student();
            student.Password = ConfirmNewPasswrod;
            student.UserId = UId;

            Student studentNewPassword = UserDB.EditStudentPassword(student, GetConfiguration().GetConnectionString("DefaultConnection"));
            return Json(studentNewPassword);
        }
        public IActionResult AmbitionSvc(long id, string ambition)
        {
            return Json(UserDB.Ambition(id, ambition, GetConfiguration().GetConnectionString(DEFAULT_CONNECTION)));
        }
        public IActionResult InviteFriends()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public JsonResult InviteUserFriend(string FriendEmail)
        {
            bool result = UserDB.InviteUserFriend(FriendEmail, GetConfiguration().GetConnectionString("DefaultConnection"));
            return Json(result);
        }
        public IActionResult ContactForm()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
        public IActionResult FAQS()
        {
            StudentModel studentModel = base.StudentModel;
            if (studentModel != null)
            {
                try
                {
                    return View(studentModel);
                }
                catch (Exception ex) {/*GetLogger().Log(LogLevel.Error, ex.Message);*/ }
            }
            return base.AssureLogin(this.CurrentController, this.CurrentAction);
        }
    }
}

INTO_WebApp/INTO/Views/Student/Booking.cshtml
@model INTO.Models.LoginModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h4>Bookings</h4>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <nav>
                                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Upcoming</a>
                                    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Previous</a>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="tab-content" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">...</div>
                                <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

INTO_WebApp/INTO/Views/Student/DashboardDisplay.cshtml
@model INTO.Models.LoginModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <link rel="stylesheet" href="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/css/site.css" />
    <link rel="stylesheet" href="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/css/cropper/cropper.css" />
    <link rel="stylesheet" href="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/css/cropper/croppie.css" />
}
@section Scripts{
    <script type="application/javascript" src="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/js/cropper/croppie.js"></script>
    <script type="application/javascript" src="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/js/cropper/cropper.js"></script>
    <script type="application/javascript" src="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/js/cropper/cam.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var ddlCountries = new Select('#ddlCountries', {
                // auto show the live filter
                filtered: 'auto',
                // auto show the live filter when the options >= 8
                filter_threshold: 8,
                // custom placeholder
                filter_placeholder: 'Select your country'
            });
            var date = new Date();
            var month = date.getUTCMonth() + 1; //months from 1-12
            var day = date.getUTCDate();
            var year = date.getUTCFullYear();

            formatteDate = year + "/" + month + "/" + day;
            //$(".date-client").html(formatteDate);
        });
    </script>
}
<div class="container">
    <form method="POST" asp-action="EditProfile" asp-controller="Student" data-role="student-profile">
        <div class="row">
            <div class="col-md-7">
                @await Html.PartialAsync("../Tutor/PictureCropper", Model)
            </div>
            <div class="col-md-5">
                <div id="avatarSpace" class="avatar mx-auto white">
                    <a id="btnProfilePicture" alt="Profile Picture" class="waves-effect waves-light" data-toggle="modal" data-target="#modalCropper">
                        <img class="contains-user-picture rounded-circle"
                             alt="Avatar">
                    </a>
                    <a role="button" class="btn btn-floating btn-outline waves-effect waves-dark square-40 square-40 ambit-save" data-role="save-std-ambition">
                        <i class="icon-save"></i>
                    </a>
                </div>
                <div class="spc-sm">
                    <p>Your main ambition(s) help tutors take good care about their attitudes and choices of most valuable explanations when delivering the idea.</p>
                    <p>It's not inappropriate nor of shame to change an ambition for some reason or simply aplly some new touches from time to time, so feel free to edit.</p>
                    <span style="visibility:hidden" class="text-error" id="lblAmbition"></span>
                    <textarea rows="6" cols="64" id="txtAmbition" placeholder="Be yourself so proudly!" class="form-control mt-4" data-role="input-std-ambition"></textarea>
                </div>
            </div>
            <button type="button" class="btn-outline-info btn-rounded light-blue lighten-5 blue-text btn-sm waves-effect waves-light preview-back">
                <svg xmlns="http://www.w3.org/2000/svg" fill="#03a9f4" height="24" viewBox="0 0 24 24" width="24">
                    <path d="M0 0h24v24H0z" fill="none" />
                    <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" />
                </svg>
            </button>

            <div class="col-md-6 mt-5">
                <div class="card" style="height:437px;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>General Details</h4>
                            </div>
                            <div class="col-md-4">
                                <div class="md-form">
                                    <button type="button" id="studentDisplayButton" class="btn btn-info btn-sm white-text light-blue darken-1 btn-profile" data-role="student-display-save">Save</button>
                                </div>
                            </div>
                            <div class="col-md-2" style="display:none;">
                                <div class="md-form">
                                    <input type="text" id="txtUserId" asp-for="@Model.User.UserId" value="@Model.User.UserId" class="form-control-sm" data-role="student-profile-Id">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <!-- First name -->
                                <div class="md-form">
                                    <input type="text" id="txtFirstName" asp-for="@Model.User.FirstName" value="@Model.User.FirstName" class="form-control-sm" data-role="student-profile-fname" required>
                                    <label data-error="wrong" for="txtFirstName" class="">First name</label>
                                    <div class="invalid-feedback">Your first name please</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <!-- Last name -->
                                <div class="md-form">
                                    <input type="text" asp-for="@Model.User.LastName" id="txtLastName" value="@Model.User.LastName" class="form-control-sm" data-role="student-profile-lastName" required>
                                    <label data-error="wrong" for="txtLastName" class="">Last name</label>
                                    <div class="invalid-feedback">Your last name please</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form">
                                    <input type="email" asp-for="@Model.User.Email" id="txtEmail" class="form-control-sm" data-role="student-profile-email" required style="width:88%;">
                                    <label data-error="wrong" data-success="right" for="txtEmail">Email</label>
                                    <div class="invalid-feedback">Your email please</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form">
                                    <input type="date" asp-for="Date" id="txtDateOfBirth" class="form-control-sm" data-role="student-profile-date" required style="width:88%;">
                                    <label data-error="wrong" data-success="right" for="txtDateOfBirth">Date Of Birth</label>
                                    <div class="invalid-feedback">Your Date Of Birth please</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mt-5">
                <div class="card">
                    <div class="card-body">
                        <h4>Previous Education</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="txtSchoolName" class="form-control-sm" data-role="student-profile-school-name" required>
                                    <label data-error="wrong" data-success="right" for="txtSchoolName">School Name</label>
                                    <div class="invalid-feedback">Your School Name please</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="txtSchoolYear" class="form-control-sm" data-role="student-profile-school-year" required>
                                    <label data-error="wrong" data-success="right" for="txtSchoolYear">School Year</label>
                                    <div class="invalid-feedback">Your School Year please</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="md-form">
                                    <select id="ddlCountries" asp-for="User.LocationSettings.Country.Id" value="User.LocationSettings.Country.Id" data-role="student-profile-country" tabindex="0" required style="width:51%;">
                                        <option value="0">Select your country</option>
                                        @foreach (var country in LoginModel.AllCountries)
                                        {
                                            <option value="@country.Id">@country.Name</option>
                                        }
                                    </select>
                                    <div class="invalid-feedback">Your country please</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="txtCity" class="form-control-sm" data-role="student-profile-city">
                                    <label data-error="wrong" data-success="right" for="txtCity">City</label>
                                    <div class="invalid-feedback">Your City please</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="txtAddress" class="form-control-sm" data-role="student-profile-address">
                                    <label data-error="wrong" data-success="right" for="txtAddress">Address 1</label>
                                    <div class="invalid-feedback">Your Address 1 please</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="txtAddress2" class="form-control-sm" data-role="student-profile-address2">
                                    <label data-error="wrong" data-success="right" for="txtAddress2">Address 2</label>
                                    <div class="invalid-feedback">Your Address 2 please</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form">
                                    <input type="text" id="txtPostCode" class="form-control-sm" data-role="student-profile-post-code" style="width:88%;">
                                    <label data-error="wrong" data-success="right" for="txtPostCode">Postcode</label>
                                    <div class="invalid-feedback">Your Postcode please</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

INTO_WebApp/INTO/Views/Student/EditPassword.cshtml
@model INTO.Models.LoginModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="card-title">Edit Password</h5>
                        </div>
                    </div>
                    @*<div class="row">
                        <div class="col-md-12">
                            <button type="button" class="btn btn-info white-text light-blue darken-1" data-role="edit-profile-password">Edit</button>
                        </div>
                    </div>*@
                    <div class="row" id="alert-success-edit-password" style="display:none;">
                        <div class="col-md-12">
                            <div class="alert alert-success" role="alert">
                                Password Changed Successfuly!
                            </div>
                        </div>
                    </div>
                    <div class="row" id="confirmPassword">
                        <div class="col-md-12">
                            <form method="POST" asp-action="EditPassword" asp-controller="Student" data-role="confirm-new-password">
                                <div class="row" style="display:none;">
                                    <div class="col-md-4">
                                        <div class="md-form">
                                            <input type="text" id="txtUserId" asp-for="@Model.User.UserId" value="@Model.User.UserId" data-role="edit-password-user-Id" class="form-control-sm">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form">
                                            <input type="text" id="txtPassword" class="form-control-sm" data-role="new-password" style="width:94%;">
                                            <label data-error="wrong" data-success="right" for="txtPAssword">New Password</label>
                                            <div class="invalid-feedback">Your new password please</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form">
                                            <input type="text" id="txtNewPassword" class="form-control-sm" data-role="confirm-new-password" style="width:94%;">
                                            <label data-error="wrong" data-success="right" for="txtNewPassword">Confirm New Password</label>
                                            <div class="invalid-feedback">Your confirm password please</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="md-form">
                                            <button type="button" class="btn btn-info white-text light-blue darken-1" data-role="edit-password" sstyle="width:100%">Edit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</div>

INTO_WebApp/INTO/Views/Student/HelpCenter.cshtml
@{
    Layout = "~/Views/Shared/MenuSupport.cshtml";
}
@section Styles {
    <link rel="stylesheet" href="@String.Format("{0}://{1}", Context.Request.Scheme, Context.Request.Host)/css/StudentCss/HelpCenter.css" />
}
<section class="section hero">
    <div class="hero-inner">
        <span style="display:block; height: 70px;"></span>
        <h1 style="color:white; font-size: 55px"> How can we help? </h1>

        <form role="search" class="search search-full" data-search="" data-instant="true" autocomplete="off" action="/hc/en-us/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓"><input type="search" name="query" id="query" placeholder="Enter a question, keyword or topic" autocomplete="off" aria-label="Enter a question, keyword or topic"></form>
    </div>
</section>
<div class="container">
    <div class="row">
        <section class="section knowledge-base">
            <section class="categories blocks">
                <ul class="blocks-list">
                    <li class="blocks-item">
                        <a href="#" class="blocks-item-link">
                            <img src="~/images/c0cb1c544c0d0bc7aaa2734c4f8eeffce50a7fd6.png">
                            <h4 class="blocks-item-title">Technical Support</h4>
                            <p class="blocks-item-description"></p>
                        </a>
                    </li>
                    <li class="blocks-item">
                        <a href="#" class="blocks-item-link">
                            <img src="~/images/5fb707b7d168da7ecdc96d56e22814d1c6311a03.png">
                            <h4 class="blocks-item-title">Help for Parents and Students</h4>
                            <p class="blocks-item-description"></p>
                        </a>
                    </li>
                    <li class="blocks-item">
                        <a href="#" class="blocks-item-link">
                            <h4 class="blocks-item-title">Help for Tutors</h4>
                            <p class="blocks-item-description"></p>
                        </a>
                    </li>
                </ul>
            </section>
        </section>
    </div>
</div>

INTO_WebApp/INTO/Views/Student/InviteFriends.cshtml
@model INTO.Models.LoginModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Give $10 , get $10</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h6>
                Invite your friends to sign up to our site. We'll give them $10 off their first lesson, and you'll get $10 when they book.
            </h6>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="card-title">Send email invite</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST" asp-action="InviteFriends" asp-controller="Student" data-role="invite-friend">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="md-form">
                                            <input type="text" id="txtEmail" class="form-control-sm" data-role="invite-via-email" style="width:100%">
                                            <label data-error="wrong" data-success="right" for="txtEmail">Your Friend's Email</label>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <button type="button" class="btn btn-info white-text light-blue darken-1" data-role="invite-friend-via-email" style="width:50%;margin-top:1.5em;float:right;">Send</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-4">
                            @*<button type="button" class="btn btn-info white-text light-blue darken-1">Share Facebook</button>*@
                            <div class="fb-share-button btn white-text" style="width:50%;float:right;"
                                 data-href="https://www.mytutor.co.uk/signup.html?rc=MYTUTOR">
                            </div>
                        </div>
                    </div>
                    </div>
            </div>
        </div>
    </div>
    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>
(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>